### ISSUE TITLE
is possible to run call with esx voice?

### ISSUE THREAD

**Issue by doublep21** [N3MTV/gcphone#105]
is possible to run call with esx voice without WEBrtc? i have issues with coturn

**Comment by Gannon001** [comment]
set "useWebRTCVocal": false in config.json

**Comment by doublep21** [comment]
i tried but does not work

**Comment by sazo2300** [comment]
@doublep21 I used my own voice resource, but the one i made set voiceprox and voicechannel every couple of seconds. If ESX voice does the same, then the issue is, that this mod sets your voiceprox and voicechannel (in the main client script). What you want to do, is either pass that responsability to the esx voice with an event, or pass a boolean to esx voice, and put the voiceprox and voicechannel inside an if statement, and pass a boolean "isInCall" to esx voice, to stop it from overruling gcphones work. 

Hope this helps you in some way

**Comment by doublep21** [comment]
was vVoice blocking the voice call thx
